### ISSUE TITLE
CI fails to authenticate causing `notebooks` and `integration` failures

### ISSUE THREAD

**Issue by jonbrenas** [malariagen/malariagen-data-python#782]
When CI runs the `notebooks` and `integration` tests, it fails to authenticate properly to GCS resulting in failures. 
<img width="1042" alt="Image" src="https://github.com/user-attachments/assets/8aaf87b9-af36-455d-93b6-cf91fe9f9333" />

It replicates with all PRs I tried so my guess is that something changed with the way CI is supposed to be authenticating.

**Comment by leehart** [comment]
My first guess is that it might be related to this in `workflows/notebooks.yml` and `workflows/integration_tests.yml`:
```
      - id: 'auth'
        name: 'Set up Google Cloud authentication'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
```
I'll see whether `GOOGLE_CREDENTIALS` has simply expired and needs refreshing.
